import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col max-w-96 m-auto h-screen`}
      >
        <div className="w-full h-11/12">{children}</div>
        <div className="flex w-full h-1/12 pt-2">
          <NavigationBar />
        </div>
      </body>
    </html>
  );
}
